Repository opensearch-project/opensearch-net, pull requests merged in 2023-11, with the labels that each got.

#427 Treat MSBuild warnings as errors
  Directory.Build.props
Labels: backport 1.x, skip-changelog

#426 Fix RemoteInfoApiTests
  tests/Tests/Cluster/RemoteInfo/RemoteInfoApiTests.cs
Labels: backport 1.x, skip-changelog

#406 Added guide for using raw JSON REST requests with low-level client.
  OpenSearch.sln
  USER_GUIDE.md
  guides/json.md
  samples/Samples/RawJsonSample/Program.cs
  samples/Samples/Samples.csproj
Labels: skip-changelog, OSCI-2023

#434 Remove duplicated paragraph from json.md guide
  guides/json.md
Labels: skip-changelog

#438 Sort usings in generated code
  src/OpenSearch.Client/_Generated/Descriptors.Cluster.cs
  src/OpenSearch.Client/_Generated/Descriptors.DanglingIndices.cs
  src/OpenSearch.Client/_Generated/Descriptors.Ingest.cs
  src/OpenSearch.Client/_Generated/Descriptors.NoNamespace.cs
  src/OpenSearch.Client/_Generated/Descriptors.Nodes.cs
  src/OpenSearch.Client/_Generated/Descriptors.Snapshot.cs
  src/OpenSearch.Client/_Generated/Descriptors.Tasks.cs
  src/OpenSearch.Client/_Generated/IOpenSearchClient.cs
  src/OpenSearch.Client/_Generated/Requests.Cluster.cs
  src/OpenSearch.Client/_Generated/Requests.DanglingIndices.cs
  src/OpenSearch.Client/_Generated/Requests.Ingest.cs
  src/OpenSearch.Client/_Generated/Requests.NoNamespace.cs
  src/OpenSearch.Client/_Generated/Requests.Nodes.cs
  src/OpenSearch.Client/_Generated/Requests.Snapshot.cs
  src/OpenSearch.Client/_Generated/Requests.Tasks.cs
  src/OpenSearch.Client/_Generated/Requests.cs
  src/OpenSearch.Net/_Generated/Api/Enums.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Cluster.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.DanglingIndices.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Ingest.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.NoNamespace.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Nodes.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Snapshot.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Tasks.cs
Labels: skip-changelog

#385 Re-generate `cluster` namespace (part 2)
  src/ApiGenerator/Configuration/CodeConfiguration.cs
  src/OpenSearch.Client/ApiUrlsLookup.cs
  src/OpenSearch.Client/Descriptors.Cluster.cs
  src/OpenSearch.Client/OpenSearchClient.Cluster.cs
  src/OpenSearch.Client/Requests.Cluster.cs
  src/OpenSearch.Client/_Generated/ApiUrlsLookup.cs
  src/OpenSearch.Client/_Generated/Descriptors.Cluster.cs
  src/OpenSearch.Client/_Generated/OpenSearchClient.Cluster.cs
  src/OpenSearch.Client/_Generated/Requests.Cluster.cs
  src/OpenSearch.Net/Api/Enums.cs
  src/OpenSearch.Net/Api/RequestParameters/RequestParameters.Cluster.cs
  src/OpenSearch.Net/OpenSearchLowLevelClient.Cluster.cs
  src/OpenSearch.Net/_Generated/Api/Enums.cs
  src/OpenSearch.Net/_Generated/Api/RequestParameters/RequestParameters.Cluster.cs
  src/OpenSearch.Net/_Generated/OpenSearchLowLevelClient.Cluster.cs
Labels: skip-changelog

#453 Cleanup old IndexTemplateV2 methods that have been replaced
  src/OpenSearch.Net/Api/RequestParameters/RequestParameters.Indices.cs
  src/OpenSearch.Net/OpenSearchLowLevelClient.Indices.cs
Labels: skip-changelog
